dtolnay/proc-macro2

- src/stable.rs
> Punctuation is joint if followed by other punctuation

- src/stable.rs
- src/strnom.rs
Fixes #12. Similar to https://github.com/dtolnay/syn/pull/152.
> Switch from IResult<I, O> to Result<(I, O), LexError>

- src/stable.rs
- src/strnom.rs
> Check for word boundary after numeric suffixes

- src/stable.rs
> Disallow space between tick and lifetime name

- src/stable.rs
> Reject keyword as lifetime name

- src/lib.rs
- src/unstable.rs
This is verified to compile and work against the current version of
rust-lang/rust#40939.
> Fill out an unstable implementation

- src/stable.rs
> Parse a bare `_` as an `Op`, not a `Term`

- src/stable.rs
- tests/test.rs
> Lex underscore in unicode escapes

- src/unstable.rs
We have one direction now. This adds the other.
> Add From<proc_macro::Span> for proc_macro2::Span.

- Cargo.toml
- src/lib.rs
> Breaking changes for 0.2

- src/stable.rs
- src/strnom.rs
See https://github.com/dtolnay/quote/issues/60
> true and false should not be parsed as literals, and should instead be parsed as terms

- src/stable.rs
- src/strnom.rs
- tests/test.rs
> Allow doc comments to be terminated with EOF

- src/lib.rs
- src/stable.rs
- src/unstable.rs
> Rename TokenStream::empty to new

- src/lib.rs
- tests/test.rs
> impl Default for TokenStream

- src/unstable.rs
Requires https://github.com/rust-lang/rust/pull/53304.
> Use TokenStream::extend

- src/lib.rs
- src/stable.rs
- src/unstable.rs
This impl mirrors the second Extend impl in libproc_macro.
> impl Extend<TokenStream> for TokenStream

- .travis.yml
- build.rs
- src/unstable.rs
This is stabilizing next week!
> Enable rich API on 1.29.0

- src/lib.rs
- src/unstable.rs
> Better panic on Span::unstable outside of proc macro

- src/fallback.rs
- tests/test.rs
> Avoid needless escape of quotes

- .travis.yml
- build.rs
- src/lib.rs
> Detect if the user has disallowed usage of the proc_macro_span feature

- src/lib.rs
Fixes alexcrichton/proc-macro2#133
> Updated the docs to mention thread-safety

- src/fallback.rs
- tests/test.rs
> Accept arbitrary lit suffixes

- src/lib.rs
> Improve docs

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
> Add 'Literal::subspan()'

- src/fallback.rs
Required for https://github.com/dtolnay/syn/issues/739.
> Implement meaningful Group::span_open/close in fallback implementation

- src/wrapper.rs
Work around https://github.com/rust-lang/rust/issues/58736 by turning panics into LexError. Closes https://github.com/dtolnay/syn/issues/749.
> Work around proc_macro::TokenStream::from_str panics

- build.rs
- src/fallback.rs
- tests/test.rs
> Match libproc_macro behavior of negative literals

- src/fallback.rs
- tests/test_fmt.rs
FYI @Koxiaet (followup to #246)
> Match libproc_macro formatting of groups

- build.rs
- src/lib.rs
- src/marker.rs
- tests/marker.rs
- tests/ui/test-not-send.stderr
> Provide UnwindSafe for all types, matching libproc_macro

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
> Implement Display and Error for LexError

- src/lib.rs
> fix typo - minor

- src/parse.rs
For the purpose of #178, if `LexError` is given a Span, *only* the `token_stream` parser needs to operate in terms of errors that have spans. The internals of the parsing only need to accept or reject the input data, without producing Span information on errors, as the parsing is structured such that those rejections are simply never propagated as errors, but just ignored:
https://github.com/alexcrichton/proc-macro2/blob/db7faa942cd491eb4e937e6fb2cf517247266950/src/parse.rs#L291-L305
> Distinguish bewteen lex errors that will and will not carry Span

- build.rs
Closes #293. This is related to the Cargo change in https://github.com/rust-lang/cargo/pull/9601.
> Recognize CARGO_ENCODED_RUSTFLAGS

- src/fallback.rs
`repr` is the terminology used in the implementation of `syn::Lit` for the string representation of a literal, and makes more sense to me in this context than `text`.
> Rename text -> repr in implementation of Literal

- src/wrapper.rs
FromStr for proc_macro::Literal was only added in Rust 1.54.
GitHub Actions was down yesterday so this didn't get caught in CI.
```console
error[E0277]: the trait bound `proc_macro::Literal: FromStr` is not satisfied
--> src/wrapper.rs:809:31
|
809 |             Literal::Compiler(repr.parse().expect("invalid literal"))
|                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `FromStr` is not implemented for `proc_macro::Literal`
```
> Restore support for versions without FromStr for proc_macro::Literal

- src/parse.rs
> Fix integer overflow in nested comment parser

- src/fallback.rs
This speeds up fuzzing from 40k exec/s (and unbounded memory usage) to 55k exec/s.
> Disable sourcemap thread_local during fuzzing

- src/parse.rs
- tests/test.rs
RFC: https://github.com/rust-lang/rfcs/pull/3348
Tracking issue: https://github.com/rust-lang/rust/issues/105723
> Implement `c"…"` literal parsing

- .github/workflows/ci.yml
¯\\\_(ツ)\_/¯ Working again. Closes #387.
> Re-enable honggfuzz CI

- src/parse.rs
> Parse rustc's representation of macro expansion error

- src/fallback.rs
- tests/test.rs
Followup to https://github.com/dtolnay/proc-macro2/pull/411#pullrequestreview-1663642603.
> Cache and lazily build the mapping from char index to byte offset

- fuzz/fuzz_targets/parse_token_stream.rs
See https://github.com/rust-fuzz/afl.rs/issues/335.
> Move cargo-afl binary from afl to cargo-afl crate

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
- tests/test.rs
> Add a function to reset thread-local span data.

- tests/test_size.rs
> Ignore size tests on non-64bit target

- src/fallback.rs
Closes https://github.com/dtolnay/syn/issues/1783.
> Perform up-front validation using the fallback parser

- src/parse.rs
> Fix spanned fallback literal construction

- .github/workflows/ci.yml
> Work around cargo-hfuzz nostart-stop-gc gold link failure

- src/parse.rs
- tests/test.rs
> Reject 'prefix#lifetime

- build.rs
Copied from https://github.com/dtolnay/anyhow/pull/354.
> Make proc_macro_span compatible with -Dwarnings

- build.rs
- src/lib.rs
- src/probe.rs
- src/probe/proc_macro_span.rs
- src/wrapper.rs
Copied from https://github.com/dtolnay/anyhow/pull/414.
> Make all use of nightly go through probed interface
