dtolnay/proc-macro2

- src/stable.rs
Right now we're parsing them as `Word(b), Literal('a')` instead of `Literal(b'a')`.
> Correctly parse byte literals like `b'a'`

- src/stable.rs
> Don't check integer literals for overflow when parsing

- Cargo.toml
- src/lib.rs
- src/stable.rs
- src/strnom.rs
Synom will need to depend on proc-macro2 as it transitions to parsing tokens instead of strings. And all of this code is being removed from synom anyway in https://github.com/dtolnay/syn/pull/147.
> Drop dependency on synom

- src/lib.rs
These derives will be available in the final `proc-macro`: https://github.com/rust-lang/rust/pull/40939#issuecomment-304751757.
> Derive Eq and PartialEq on OpKind and Delimiter

- .travis.yml
- Cargo.toml
- src/stable.rs
- tests/compile-fail/symbol_send.rs
- tests/compile-fail/symbol_sync.rs
- tests/compiletest.rs
Fixes #24.
I don't know how to write a test for this. Any ideas? :cry: 
I tried this but the impls conflict:
```rust
trait NotSend {}
impl<T> NotSend for T where T: Send {}
// Would fail if Symbol is Send
impl NotSend for Symbol {}
```
> Remove Send and Sync for Symbol

- src/lib.rs
I don't see a reason why it shouldn't be `Eq`/`PartialEq`... but I hardly know anything about proc macros, so I'm probably wrong ^_^
> Derive `Eq/PartialEq` for `Spacing`

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/stable.rs
- src/strnom.rs
- src/unstable.rs
- tests/test.rs
This doesn't add support for the diagnostic methods on `Span` in stable rust. Perhaps we should add support for that, but I'm not sure what it would look like & I don't think we want a diagnostics engine in proc-macro2.
It does add support for things like fetching the line and column numbers of the start and end of a span.
> Support meaningful spans in the stable version of proc-macro2

- .travis.yml
- src/lib.rs
- src/stable.rs
- src/strnom.rs
- tests/test.rs
`Token![...]` being 24 bytes is a large number.
> Omit Span::lo/hi when not using procmacro2_unstable

- src/lib.rs
- src/unstable.rs
This is a way to expose the diagnostics API without a large surface area in proc_macro2. Sergio needed this for a [demo](https://github.com/SergioBenitez/syn/tree/next/examples/unstable).
```rust
let a = parser.parse::<ExprTuple>()?;
parser.parse::<token::Eq>()?;
let b = parser.parse::<ExprTuple>()?;
parser.eof()?;
let (a_len, b_len) = (a.elems.len(), b.elems.len());
if a_len != b_len {
return Err(b.span().unstable()
.error(format!("expected {} element(s), got {}", a_len, b_len))
.span_note(a.span().unstable(), "because of this"));
}
```
> Span::unstable to expose the proc_macro::Span

- .travis.yml
- Cargo.toml
- README.md
- src/lib.rs
- src/stable.rs
- src/strnom.rs
- src/unstable.rs
- tests/test.rs
The RUSTFLAGS cfg is now `--cfg procmacro2_semver_exempt` and the Cargo one is `--features proc-macro2/nightly`. This clarifies the difference between these two basically orthogonal flags. Fixes #42.
> Rename procmacro2_unstable and proc-macro2/unstable

- src/stable.rs
- tests/test.rs
Previously `Literal::float` could print as something that parsed as an integer.
> Ensure that float literal is always formatted as floating point

- src/lib.rs
- src/stable.rs
- src/unstable.rs
Added upstream in https://github.com/rust-lang/rust/pull/47149.
Proc macro spans serve two mostly unrelated purposes: controlling name resolution and controlling error messages. It can be useful to mix the name resolution behavior of one span with the line/column error message locations of a different span.
In particular, consider the case of a trait brought into scope within the def_site of a custom derive. I want to invoke trait methods on the fields of the user's struct. If the field type does not implement the right trait, I want the error message to underline the corresponding struct field.
Generating the method call with the def_site span is not ideal -- it compiles and runs but error messages sadly always point to the derive attribute like we saw with Macros 1.1.
```
|
4 | …
```
> Span::resolved_at and Span::located_at to combine behavior of two spans

- src/lib.rs
- src/stable.rs
- src/unstable.rs
Cleanup only, does not affect the public api.
> Use the same api for imp::Term as for Term

- src/strnom.rs
- tests/test.rs
Looks like they didn't fall into quite the right position!
Closes #57
> Add a special case for empty `/*` comments

- .travis.yml
- Cargo.toml
- src/lib.rs
- src/stable.rs
This commit adds a feature to this crate which enables linking to the
upstream `proc_macro` crate. This should help this compile on targets
which don't have `proc_macro` and allow it to also be suitable for
embedding in Rust binaries.
This feature is turned on by default for backwards compatibility right
now.
> Add a feature for linking to `proc-macro`

- Cargo.toml
- src/lib.rs
- src/macros.rs
- src/stable.rs
- src/unstable.rs
- tests/test.rs
More information to come later about this, but this is a result of the
work week discussions we've had about stabilizing procedural macros
> Reimplement public interface for stability

- src/lib.rs
- src/stable.rs
- src/unstable.rs
This commit continues to prepare this crate for being reimplemented in terms of the upstream `proc_macro` API, mostly changing how the stable `src/lib.rs` interfaces with the stable/unstable modules. No functional change is intended as part of this PR.
> Tweak implementation details for upcoming changes

- src/stable.rs
- src/strnom.rs
- tests/test.rs
This means they no longer round trip but it should be more faithful to what
macro_rules! is doing
Closes #73
> Lex doc comments as attributes

- src/stable.rs
- tests/test.rs
Without this, all sorts of crazy terms are accepted and handled incorrectly downstream.
> Validate input in Term::new

- .travis.yml
- src/lib.rs
- src/stable.rs
- src/strnom.rs
- src/unstable.rs
This commit is a stab at getting the `proc_macro2` crate to function outside the
context of the compiler, **even when the `nightly` feature is enabled**.
Previously when the `nightly` feature was enabled then `proc_macro2` would panic
at runtime because `proc_macro` itself would panic at runtime due to the lack of
the compiler being initialized.
In this commit the `unstable` module in `proc_macro2` no longer unconditionally
uses the `proc_macro` upstream crate but is rather an `enum` over the upstream
crate and the `stable` module. At runtime the appropriate implementation is
dynamically selected depending on which works.
This brings up some uncomfortable issues such as what happens when you try to
psas a "stable span" to a "nightly `Literal`", but I think we can paper over
these issues …
> Fix the `nightly` feature outside of rustc

- Cargo.toml
- README.md
- src/lib.rs
- src/stable.rs
- src/unstable.rs
- tests/test.rs
* Rename `Term` to `Ident`
* Rename `Punct` to `Op`
* Remove `Term::as_str`
* Rename `Op::op` to `Punct::as_char`
* `Term::new` no longer accepts lifetimes or raw idents
* Lifetimes are lexed as a `Joint` `'` character followed by an `Ident`
* `Ident::new_raw` is a new `procmacro2_semver_exempt` API for creating raw
identifiers.
* `{Eq,PartialEq,Ord,PartialOrd,Hash} for Ident`
* Remove `Copy for Term`
* Remove `Copy for Op`
* Add `Extend<TokenTree> for TokenStream`
> Track upstream proc_macro changes

- src/stable.rs
- tests/test.rs
Technically a breaking change but 0.4 is so new I'm tempted to leave this as
0.4.1
Closes #87
> Parse `_` as an ident

- src/lib.rs
This is the signature of the [PartialEq impl from Syn 0.13](https://docs.rs/syn/0.13/syn/struct.Ident.html#implementations) which has worked great. It avoids `ident.to_string() == "..."` which triggers a negative reaction in many users in my experience.
> Ident == AsRef<str>

- src/stable.rs
Because they're very common. rustc's lexer has the same optimization.
This speeds up various runs of `cargo` in rustc-perf, the best by 4%.
I admit to not understanding how `proc-macro2` is used when rustc builds `cargo`. I don't need to recompile rustc for the changes to take effect, speedwise, so somehow `proc-macro2` must be both compiled and run while `cargo` is being compiled.
> Handle ASCII identifiers quickly.

- src/lib.rs
- src/stable.rs
This causes the `proc-macro` feature to be ignored for wasm-targets where proc-macro is not available. Currently, if a crate is to be built that depends on `proc-macro2`, the `proc-macro` feature from an actual proc-macro leaks into the build-environment of `proc-macro2` even if `default-features = []`, causing the build to fail.
This patch enables me to build (and run) my crate on wasm-targets.
I don't know if the patch is actually fully correct or not. If it is, it would be nice to be pushed into a 0.4.10-release. `stdweb` has [recently](https://github.com/koute/stdweb/issues/257) bumped its dependencies in order to wait for this patch in `0.4`. There are also patches like this waiting for `quote` and `syn`.
> Ignore proc-macro feature on wasm-target

- Cargo.toml
The build script from https://github.com/alexcrichton/proc-macro2/commit/5354848b97357fce067d2edad5de614e084c8888 is not picked up automatically pre-1.17 so those compilers were not building with `use_proc_macro` even though that should have been the default.
> Restore compatibility with rustc 1.15-1.16

- build.rs
This reverts commit f3d1b2c7818be3fc8f856433092b91c6a8b8cbeb. Fixes https://github.com/dtolnay/syn/issues/470.
> Revert "Disable linking to `proc_macro` on musl"

- README.md
- build.rs
- src/lib.rs
- src/unstable.rs
This commit detects the rustc version in the build script of proc-macro2
to determine whether the compiler supports the necessary backend APIs.
This should hopefully allow the crate to compile on stable by default
but have a better implementation on 1.30.0+ compilers.
> Automatically use rich API on 1.30.0+

- src/unstable.rs
> Hide panic output in nightly_works

- src/lib.rs
- src/stable.rs
- src/unstable.rs
The second of these impls is very hot in Syn. This commit improves performance by 15% when executing in stable mode, dropping the time to parse all of rust-lang/rust + submodules from 7.8 seconds to 6.6 seconds.
> Optimize PartialEq impls for Ident

- .travis.yml
The `procmacro2_semver_exempt` feature tracks whatever is in nightly, so we reserve the right to remain broken on compilers that are not nightly.
Per https://github.com/alexcrichton/proc-macro2/pull/128#issuecomment-419167363.
> Remove semver exempt testing from 1.15 and stable builds

- src/lib.rs
- src/stable.rs
- src/unstable.rs
These were added to libproc_macro in https://github.com/rust-lang/rust/pull/53902.
Requires factoring out an `imp::Group` to preserve the original `proc_macro::Group` in the nightly case, because deconstructing a group into delimiter/stream/span causes its span_open and span_close to be lost.
```diff
impl Group {
+     #[cfg(procmacro2_semver_exempt)]
+     pub fn span_open(&self) -> Span;
+     #[cfg(procmacro2_semver_exempt)]
+     pub fn span_close(&self) -> Span;
}
```
> Provide Group::span_open and span_close

- src/lib.rs
As per my extra comment to #132 this adds the def_site feature to proc-macro2 so it'll compile with the latest nightly.
> Adds def site feature to super-unstable

- build.rs
- src/lib.rs
- src/stable.rs
- src/unstable.rs
Only compile in this support if rustc is new enough, otherwise continue
to omit the bindings for older-than-1.26 rustc
Closes #143
> Add support for 128-bit integers

- .travis.yml
- build.rs
procmacro2_semver_exempt is working on rust < 1.29, but
since 1.29, proc_macro2 forward to proc_macro even when
procmacro2_semver_exempt is set, which require a nightly
compiler
> Allow to use procmacro2_semver_exempt on stable rust

- .travis.yml
- Cargo.toml
- build.rs
- src/lib.rs
- tests/test.rs
Before this PR, enabling procmacro2_semver_exempt would disable wrap_proc_macro, meaning that real spans would not be preserved by proc macros. One would also need to enable the "nightly" feature in order to preserve spans when using procmacro2_semver_exempt.
This PR automatically enables wrap_proc_macro when building with procmacro2_semver_exempt on a nightly compiler.
> Infer nightly feature on nightly toolchain

- .travis.yml
- README.md
- src/lib.rs
Older compilers ignore the ```` ```edition2018```` code blocks which is why we no longer need different Travis scripts for them.
> Update documentation to 2018 edition

- build.rs
- src/lib.rs
- src/wrapper.rs
The method is not unstable because you can call it from a procedural macro on a stable compiler. The name unwrap indicates that it panics if not present, i.e. if not inside of a proc macro like the method documentation talks about.
> Rename Span::unstable to Span::unwrap

- src/lib.rs
Fixes #83. These derives match https://doc.rust-lang.org/nightly/proc_macro/struct.LineColumn.html.
> Derive traits for LineColumn

- src/fallback.rs
Fixes #156. This matches the renames in https://github.com/rust-lang/rust/issues/51574 / https://github.com/rust-lang/rust/pull/55190. Does not affect public API.
> Rename codemap to source map

- src/lib.rs
- src/wrapper.rs
Both the wrapper and fallback versions are cloneable.
This brings proc_macro2 in line with proc_macro in terms of this
functionality.
> Make TokenStream's IntoIter derive Clone

- .travis.yml
- Cargo.toml
- src/lib.rs
- tests/features.rs
I was working on a separate PR when I noticed that adding `--no-default-features` to `cargo test` didn't actually disable the `proc-macro` feature. Turns out the `quote` dev-dependency was sneakily reactivating that feature through its own default feature.
When I fixed that, one of the doc tests failed to compile, so I fixed that as well.
I also added an `#[ignore]`'d test that asserts that `proc-macro` is disabled, and told travis to run that test when using `--no-default-features`. That's a little wacky but it's the best way I can think of to prevent this happening again.
> Actually allow disabling proc-macro feature in tests

- src/wrapper.rs
Fixes #198 by batching invocations of the `impl Extend<TokenTree> for TokenStream` impl.
For the benchmark in https://github.com/illicitonion/num_enum_regression_13 this reduces compile time from 118 seconds to 2.0 seconds on my machine.
Once the Extend performance is fixed in libproc_macro (https://github.com/rust-lang/rust/issues/65080), this commit should be reverted.
> Defer calls to proc_macro::TokenStream::extend

- src/fallback.rs
Using escape_debug instead of escape_default matches the behavior of libproc_macro for:
```rust
println!("{:#?}", "///こんにちは世界".parse::<TokenStream>().unwrap());
```
Before: `"\u{3053}\u{3093}\u{306b}\u{3061}\u{306f}\u{4e16}\u{754c}"`
After: `"こんにちは世界"`
Fixes https://github.com/dtolnay/syn/issues/772.
> Don't escape_default all non-ascii text

- src/detection.rs
- src/fallback.rs
- src/lib.rs
This adds a function `proc_macro2::fallback::force()` to force use of proc-macro2's fallback implementation of the API beginning at that point, even if the compiler's implementation is available, and a function `proc_macro2::fallback::unforce()` to resume using the compiler's implementation of the proc macro API if available.
Closes #216. Closes #219.
> Add a way to force fallback implementation

- src/fallback.rs
#126
```rust
fn main() {
let path = "../rust/src/librustc_ast/util/parser.rs";
let content = std::fs::read_to_string(path).unwrap();
for _ in 0..1000 {
content.parse::<proc_macro2::TokenStream>().unwrap();
}
}
```
```bash
cargo build --release  
valgrind --tool=callgrind target/release/bench_proc
callgrind_annotate --auto=yes callgrind.out.*
```
This one step, it eat about 300M ir.
I can improve it much more but it needs a refactor, the `alt!` macros they are not efficient and the common logic is repeated many times, the most called `skip_whitespace` but there are also others like `fallback::token_kind`, `fallback::op_char` ...
If you like, I continue.
> Fix multiple unnecessary calls to strnom::skip_whitespace

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
This adds support for hygiene-related APIs recently stabilized for Rust 1.45 (currently nightly).
* `mixed_site` was stabilized in https://github.com/rust-lang/rust/pull/68716.
* `resolved_at` and `located_at` were stabilized in https://github.com/rust-lang/rust/pull/69041
The Cargo feature is named following the overarching `proc_macro_hygiene` language feature [also about to be stabilized](https://github.com/rust-lang/rust/pull/68717), which itself doesn't add any API surface for `proc_macro2`. 
Closes #210
> Add `Span::mixed_site`, `Span::resolved_at`, and `Span::located_at` behind `hygiene` feature

- src/fallback.rs
- src/parse.rs
- tests/test.rs
We now store the character offset in `Cursor.off` and keep track of characters where it matters: idents, strings, char literals, comments and doc comments.
FWIW I've "fuzzed" this against Rust's codebase to find panics:
```rust
use proc_macro2::*;
use std::str::FromStr;
fn main() {
let args: Vec<_> = std::env::args().skip(1).collect();
if args[0] == "--single" {
visit(&args[1]);
} else {
let files = std::fs::read_to_string(&args[0]).unwrap();
for file_name in files.lines() {
visit(file_name);
}
}
}
fn visit(file_name: &str) {
println!("{:?}", file_name);
let source = std::fs::read_to_string(file_name).unwrap();
let iter = TokenStream::from_str(&source).unwrap().into_iter();
#[cfg(span_locations)]
for tree in iter {
let span = tree.span();
let _ = span.end();
let _ = span.start();
}
}
``` …
> Use character-based offsets in `Span`

- src/parse.rs
This implementation is about 14% faster on a representative source file (I used https://github.com/rust-lang/rust/blob/2c462a2f776b899d46743b1b44eda976e846e61d/src/libcore/str/mod.rs) and also makes fuzzing easier because we no longer overflow the stack.
> Eliminate recursion from token stream parser

- src/lib.rs
Corresponding proc_macro PR: https://github.com/rust-lang/rust/pull/72446.
> Impl Ord for LineColumn

- src/fallback.rs
This allows a non-macro tool that uses `proc-macro2 = { default-features = false }` to contain an unconditional call to `proc_macro2::fallback::force()` (#220). Previously, such a tool would either need to not use `default-features = false`, or not use `proc_macro2::fallback::force()` and hope that nothing else in the dependency graph enables proc-macro2's default feature.
> Don't gate force/unforce on wrap_proc_macro

- src/wrapper.rs
I dropped the following code (below; extracted from https://github.com/rylev/winrt-profile) into a dummy proc macro crate to measure the impact on winrt's code generation.
Basically it seems there are two things it's sensitive to:
- Reducing the number of calls over the proc macro bridge (roughly: number of times anything in real proc_macro gets called) can significantly improve performance.
- Reducing various overheads in the proc-macro2 wrapper layer can significantly improve performance.
This PR includes two commits, one of each type. There are certainly more of each left to do. So far in total this improves expansion time by 10%.
---
```rust
use proc_macro2::TokenStream;
use std::fs;
use std::time::Instant;
use winrt_gen::{NamespaceTypes, TypeLimit, TypeLimits, TypeReader, TypeStage, …
```
> Improve debug mode perf of proc_macro wrapper

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
> Remove procmacro2_semver_exempt feature gate on all methods stabilized in rustc 1.45

- src/fallback.rs
This also fixes an issue where `quote!((1 + 2)).to_string()` outputs `( 1 + 2 )` in fallback mode but `(1 + 2)` in regular mode.
> Improve fallback Display impl for TokenStream

- src/parse.rs
- tests/test.rs
Previously e.g. `0o0A` would fail to lex because `A` is not a permissible octal digit. It doesn't need to be a digit though. This is an octal literal `0o0` with suffix `A`.
This matches libproc_macro's behavior which parses it as:
```rust
Literal {
kind: Integer,
symbol: "0o0",
suffix: Some("A"),
span: #7 bytes(88..92),
}
```
https://github.com/dtolnay/syn/issues/897
> Parse integer suffix beginning with a hex digit

- src/parse.rs
- tests/test.rs
Previously we'd just pass over as many consecutive `-`/`+` signs as the caller felt like, which is not correct. `0E--0`
https://github.com/dtolnay/syn/issues/897
> Reject duplicate sign in float literal

- src/parse.rs
This had no observable effect. We'll lex the same token as an integer literal in the next branch of `literal_nocapture`.
https://github.com/alexcrichton/proc-macro2/blob/e45143b61b2da784f64ee69349db6cbb3e6f8f93/src/parse.rs#L297-L301
> Remove special case on f32/f64 suffix

- src/parse.rs
- tests/test.rs
Previously `0.0asdf` would parse as a float literal with suffix `asdf` but `0.0ECMA` would not parse as a float literal with suffix `ECMA`.
> Parse float suffix beginning with `E`

- src/parse.rs
- tests/test.rs
Rustc rejects unicode escapes longer than 6 digits, not including `_`.
```console
error: overlong unicode escape (must have at most 6 hex digits)
--> src/main.rs:2:14
|
2 |     let _ = "\u{0000000}";
|              ^^^^^^^^^^^
```
> Allow only at most 6 digits in unicode escape

- src/parse.rs
- tests/test.rs
- ~~`"\u{999999}"`~~
- ~~`"\u{}"`~~
- ~~`"\u{_0}"`~~
> Disallow unicode escapes that are out of range, empty, or begin with underscore

- src/parse.rs
- tests/test.rs
This is disallowed by rustc (though notice that the diagnostic is hilariously actually returning the carriage):
```console
error: bare CR not allowed in raw string
--> src/main.rs:2:15
|
";|     let s = r"
|               ^
```
> Disallow bare carriage return in raw string literal

- src/parse.rs
- tests/test.rs
Carriage return is only accepted if immediately followed by a newline, whether or not the carriage return is preceded by `\`.
> Require newline after backslash carriage return

- src/parse.rs
- tests/test.rs
This is not lexed as two consecutive lifetime tokens in Rust.
```rust
macro_rules! m {
($($tt:tt)*) => {};
}
m!('aa'aa);
```
```console
error: character literal may only contain one codepoint
--> src/main.rs:5:4
|
5 | m!('aa'aa);
|    ^^^^
|
help: if you meant to write a `str` literal, use double quotes
|
5 | m!("aa"aa);
|    ^^^^
```
> Disallow lifetime followed immediately by single quote

- src/lib.rs
- src/parse.rs
- src/wrapper.rs
- tests/test.rs
Op is the old name of Punct, prior to https://github.com/rust-lang/rust/pull/50473 (https://github.com/rust-lang/rust/commit/47d4089e100f6a1e19e8687158cc1e0c71ac2ae3).
This PR replaces `op` with `punct` in variable names and function names, and replaces the private `Punct::op` field with `Punct::ch` which is rendered by the Debug impl as `char`, reflecting that it's the character you get by calling as_char on the Punct.
> Replace ancient `op` naming

- tests/test.rs
> Confirm that fallback TokenStream can preserve jointness of last punct

- src/lib.rs
Helps #237
**What it does:**
- Adds warning on methods `Span::start` and `Span::end` methods
> FIX - Document mocked Span::start and Span::end methods

- src/parse.rs
Two places had code resembling:
```rust
match $expr {
Ok($var) => $result,
Err(LexError) => Err(LexError),
}
```
which is better expressed by:
```rust
let $var = $expr?;
$result
```
> Simplify `Err(LexError) => Err(LexError)` arms in parser

- src/lib.rs
#268 is not accurate; `start`/`end` work perfectly fine on stable as long as you aren't in a proc macro.
> Document behavior of Span::start/end outside of proc macro

- Cargo.toml
- src/lib.rs
Similar to https://github.com/dtolnay/syn/pull/925 -- see the purple notices on the `parse_*` methods of https://docs.rs/syn/1.0.67/syn/punctuated/struct.Punctuated.html.
<br>
> Render doc(cfg) notices on docs.rs

- src/fallback.rs
- src/parse.rs
The previous factoring, of having FromStr perform both the parse and the check for whether the complete input was parsed, is leftover from prior to #231 when the `token_stream` parser used to need to invoke itself recursively to parse the content of nested groups. That is no longer the case so `token_stream` can be responsible for the whole thing, including returning error on unparseable trailing characters.
> Move check for full parse into token_stream parser

- src/parse.rs
There is only one single place that this loop terminates with a `break` (as opposed to `return`), and that is when the input runs out of bytes. Replace that break with returns, making it clear that there is no need for the `input.is_empty()` check at that point.
> Simplify token parse loop termination

- src/fallback.rs
- src/lib.rs
- src/parse.rs
- src/wrapper.rs
Closes #178.
This PR adds `impl LexError { pub fn span(&self) -> Span }`. While libproc_macro's LexError does not have such a method, having this is far more important for proc-macro2 than for libproc_macro, because proc macro input is *already lexed* by rustc and receives good rustc-generated diagnostics on lex errors, while main.rs / build.rs-based parser do not get that.
<br>
```console
error: lex error
┌─ src/main.rs:1:1
│
1 │ //! this file contains a lex error... where?
│ ^ lex error
```
```console
error: lex error
┌─ src/main.rs:46:12
│
46 │ fn main() {)
│            ^ lex error
```
> Add span to lex errors

- src/fallback.rs
- src/lib.rs
- src/parse.rs
- src/wrapper.rs
- tests/test.rs
Corresponds to the libproc_macro impl added by https://github.com/rust-lang/rust/pull/84717.
> impl FromStr for Literal

- build.rs
- src/wrapper.rs
Closes #287 now that https://github.com/rust-lang/rust/pull/84717 has made it into a stable Rust release.
> Use real Literal::from_str from libproc_macro

- src/detection.rs
In #300 I made a mistake with the `#[cfg]` causing `proc_macro::is_available()` to never actually be used. I have now double checked that it is actually used on Rust 1.57+.
Closes https://github.com/bjorn3/rustc_codegen_cranelift/issues/1101
Closes https://github.com/bjorn3/rustc_codegen_cranelift/issues/1209
> Fix usage of proc_macro::is_available()

- build.rs
- src/detection.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
It's better for *absence* of features to give you compatibility with our newest supported stable compiler, instead of our oldest supported one. This makes the most complete API available to non-Cargo build systems and direct `rustc` invocations without them needing to keep up with all the cfgs the proc-macro2 build script deals with.
> Invert cfgs that deal with old compiler support

- build.rs
- src/wrapper.rs
These were stabilized in 1.55.0 by https://github.com/rust-lang/rust/pull/86136.
> Enable span_open() and span_close() on Rust 1.55+

- src/parse.rs
This reduce useless allocations.
> doc_comment: consume vector instead of iterating and collecting it

- build.rs
Closes #309. See analysis in https://github.com/rust-lang/docs.rs/issues/1580 of the docs.rs change that broke this.
> Work around doc build failure due to docs.rs flags change

- src/lib.rs
Cargo's logic for what `cfg` get passed to the build script build, what to the library build, and what to the documentation build is apparently super subtle. See the discussion under https://github.com/rust-lang/docs.rs/issues/1580.
> Try to diagnose "cannot find type SourceFile" errors better

- src/detection.rs
The `WORKS` atomic is not synchronizing anything else outside of its own value, so the SeqCst ordering is unnecessary.
> Ordering::Relaxed for the proc_macro detection

- benches/bench-libproc-macro/README.md
This has been running hundreds of times faster since Rust 1.40, due to https://github.com/rust-lang/rust/issues/65080 / https://github.com/rust-lang/rust/pull/65198.
> Update benchmark example output

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
This is intended for the `quote!` macro to use when constructing a proc-macro2 token out of a macro_rules $:literal token, which is already known to be a valid literal. This avoids reparsing/validating the literal's string representation.
This is not public API other than for quote.
> Add a Literal::from_str_unchecked constructor for quote

- src/fallback.rs
- src/parse.rs
For optimization I am working on, it's useful to guarantee that this isn't read or mutated by any other module.
> Reduce visibility of fallback TokenStream's field

- build.rs
In the case that neither `CARGO_ENCODED_RUSTFLAGS` nor `RUSTFLAGS` is set, we don't need to bother with making an `iter::empty()`. The function will always return `true` after looping 0 times, since `-Z allow-features=` cannot be present.
> Simplify env var handling in build script

- build.rs
`RUSTFLAGS` is no longer ever set during build script execution since rust 1.55, so we don't need to bother looking for it. See https://github.com/rust-lang/cargo/issues/10111.
> Delete RUSTFLAGS fallback from build script

- Cargo.toml
- src/fallback.rs
As of version 0.2.2, unicode-xid has its own fast path for ASCII identifiers added by https://github.com/unicode-rs/unicode-xid/pull/20.
> Rely on unicode-xid to optimize ASCII properly

- src/fallback.rs
As raised by this Clippy lint:
```console
error: `format!(..)` appended to existing `String`
--> src/fallback.rs:879:22
|
879 |                 _ => escaped.push_str(&format!("\\x{:02X}", b)),
|                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
|
= note: `-D clippy::format-push-string` implied by `-D clippy::all`
= help: consider using `write!` to avoid the extra allocation
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#format_push_string
```
> Eliminate an allocation from Literal::byte_string

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
- tests/test.rs
The previous Compiler behaviour appears to have been broken, in that it
would return a non-raw string literal, so it was replaced with the
[fallback code from quote][1].
[1]: https://github.com/dtolnay/quote/blob/eeabf0d42ed68418741542ab5cfa8a9d339f8a79/src/runtime.rs#L409-L422
This will be needed to fix https://github.com/dtolnay/quote/issues/223
> Mark Ident::new_raw as no longer semver-exempt

- src/fallback.rs
Keep the panicks together.
Structuring it this way reveals that it isn't even possible for `string` to be `""` or `"$crate"` or `"{{root}}"` at the location that the validation happens. I will delete those cases in a separate PR.
> Move raw ident validate into validate_ident

- src/fallback.rs
`""` is ruled out by the check for `if string.is_empty()` at the top. `"$crate"` and `"{{root}}"` are ruled out because their first character does not pass `is_ident_start`.
> Delete unreachable cases from raw identifier check

- src/lib.rs
- tests/test.rs
In libproc_macro mode this won't take effect until the upstream PR lands: https://github.com/rust-lang/rust/pull/99703. But in fallback mode it should work right away.
> Expose size_hint() for TokenStream's iterator

- src/fallback.rs
The data structure for TokenStream currently in proc-macro2 is a bad fit for the API we inherit from libproc_macro. Specifically this problematic part:
```rust
impl Group {
pub fn stream(&self) -> TokenStream;
}
```
This function, along with the lack of by-reference iterator on TokenStream, means that the *only* possible way to parse tokens ends up performing quadratically many token clones. For example if you start with a TokenStream representing `( ( ( ( a ) ) ) )`,  parsing it involves:
- calling into_iter() to get an iterator of TokenTree;
- you'll find in there a Group, so call stream(); this clones the tree's entire contents `( ( ( a ) ) )`
- call into_iter()
- call stream(), which clones `( ( a ) )`
- call into_iter()
- call stream(), which clones `( a )`
- call into_iter()
- call …
> Reference count TokenStream in fallback mode

- src/fallback.rs
- src/parse.rs
There is no immediate behavior change here, but this refactor is necessary for #336. When building a TokenStream in the parser we don't want to allocate all the tokens in an ordinary Vec and then have to copy the whole thing into an RcVec. We can allocate them directly in a statically-uniquely-owned RcVec up front.
> Remove Vec from API of fallback::TokenStream

- src/fallback.rs
- src/parse.rs
We have one method that deals with https://github.com/dtolnay/proc-macro2/issues/235, splitting the negative sign out of negative literal tokens from the proc-macro API, and a separate method that only handles tokens coming from the parser which are never negative literals.
> Rename the two different token push methods

- src/lib.rs
- src/wrapper.rs
Libproc_macro does not provide `Debug` for `token_stream::IntoIter`. I think it's an oversight that we have it in this crate, but we might as well make it not useless.
> Improve Debug representation of token_stream::IntoIter

- src/fallback.rs
- src/lib.rs
- src/rcvec.rs
Part of #336. This refactor keeps the underlying representation still as `Rc<Vec<T>>`, but reveals the complete API surface that we are going to need a reimplementation for as part of improving the representation.
> Replace Rc<Vec<T>> with RcVec<T>

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
Tracking issue: https://github.com/rust-lang/rust/issues/87552
> Expose proc_macro's before() and after() methods on Span

- src/parse.rs
Repro:
```rust
fn main() {
_ = "r#self".parse::<proc_macro2::TokenStream>();
}
```
This used to panic, now it will return an error.
```console
$ cargo run
thread 'main' panicked at '`r#self` cannot be a raw identifier', proc-macro2/src/fallback.rs:756:17
```
> Fix panic on parsing disallowed raw identifier in fallback mode

- src/fallback.rs
- src/parse.rs
- tests/test.rs
> Handle parsing input that starts with byte order mark

- src/fallback.rs
- src/lib.rs
- src/location.rs
- src/wrapper.rs
Previously there were 3 separate redefinitions of the same LineColumn struct.
> Deduplicate implementations of LineColumn

- src/parse.rs
- tests/test.rs
https://github.com/rust-lang/rust/pull/95251
> Reduce max hash in raw strings to 255

- src/extra.rs
- src/fallback.rs
- src/lib.rs
For getting the span of an opening punctuation or closing punctuation of a group, `proc_macro` only lets you use `span_open()` and `span_close()` if you still have *the original `Group`* that came in through the macro input. If you just have the group's `Span`, there is no possible way to split that into `span_open` and `span_close` after the fact (even though rustc is capable of doing this operation). You can't even fool it by doing `let mut tmp = Group::new(Delimiter::Parenthesis, TokenStream::new()); tmp.set_span(span); tmp.span_close()` -- this will just give you back `span` instead of the correct `span_close`.
Libraries sometimes want to keep track of delimiter spans separately from contents. An example of this is `syn::MacroDelimiter` -- …
> Add DelimSpan to hold the 3 different spans of a delimiter

- src/extra.rs
- src/fallback.rs
- src/lib.rs
- src/parse.rs
- src/wrapper.rs
A few things left over from #162.
> Rename 'stable' terminology to 'fallback'

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
> Expose proc_macro's source_text() on Span

- src/fallback.rs
- src/parse.rs
- tests/test.rs
Previously Literals parsed using FromStr would always have a useless call_site() span, meaning that source_text() would not work on them.
> Create meaningful span for Literal in FromStr

- src/fallback.rs
- tests/test.rs
> Circumvent clippy::octal_escapes lint in generated literals

- src/fallback.rs
- tests/test.rs
Previously libcore 1.60 and older would render \0 as `\u{0}` while 1.61+ would render `\0`.
> Implement consistent behavior for Literal::string on all versions of Rust

- src/rcvec.rs
Previously it was not the case on versions from 1.32 through 1.57.
```console
error[E0277]: the type `UnsafeCell<usize>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
--> tests/marker.rs:13:13
|
13 |               assert_implemented::<$ty>();
|               ^^^^^^^^^^^^^^^^^^^^^^^^^ `UnsafeCell<usize>` may contain interior mutability and a reference may not be safely transferrable across a catch_unwind boundary
...
82 | /     assert_unwind_safe! {
83 | |         Delimiter
84 | |         Group
85 | |         Ident
...  |
92 | |         TokenTree
93 | |     }
| |_____- in this macro invocation
|
= help: within `proc_macro2::Group`, the trait `RefUnwindSafe` is not implemented for `UnsafeCell<usize>`
= note: required because …
```
> Ensure data structures are RefUnwindSafe on all versions of Rust

- src/wrapper.rs
This API is in flux upstream. https://github.com/rust-lang/rust/pull/111571
> Disable start()/end() on Span::Compiler

- build.rs
When compiling for target `wasm32-unknown-emscripten`, `proc_macro` should be enabled. To see a simple repro of why, do the following:
* Create a new empty lib crate with `syn` as a dependency.
* `cargo build --release --target wasm32-unknown-emscripten`. Note this target is *not* `wasm32-unknown-unknown`, which does compile successfully.
You'll see that the build fails with:
```
error[E0277]: the trait bound `proc_macro2::TokenStream: From<proc_macro::TokenStream>` is not satisfied
--> /Users/rickweber/.cargo/registry/src/github.com-1ecc6299db9ec823/syn-2.0.16/src/buffer.rs:69:27
|
69 |         Self::new2(stream.into())
|                           ^^^^ the trait `From<proc_macro::TokenStream>` is not implemented for `proc_macro2::TokenStream`
|
= help: the trait …
```
> enable proc_macro on wasm32-unknown-emscripten

- build.rs
This code is originally from #111. As of Rust 1.32 (https://github.com/rust-lang/rust/pull/49219) it seems no longer needed.
> Extern crate proc_macro available on all wasm targets

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
Unblocks https://github.com/rust-lang/rust/pull/111571.
> Delete use of proc_macro::Span::before/after

- src/parse.rs
- tests/test.rs
This PR ports https://github.com/dtolnay/syn/pull/1381 from syn's literal parser to proc-macro2's literal lexer.
Before this PR, `"b\"\\\n\u{a0}\""` would parse successfully as a byte string literal token. The trailing backslash would skip over all following Unicode whitespace, including the non-breaking space codepoint. This behavior was incorrect. Trailing backslash is only supposed to skip over ASCII space, `\t`, `\n`, and `\r\n`. Non-ASCII codepoints such as nbsp are not allowed in the representation of a byte string literal.
> Stricter parsing of string_continue escapes in cooked string

- src/parse.rs
- tests/test.rs
`br"☃"` is not supposed to be considered a valid byte string literal.
> Disallow non-ASCII content inside byte string

- src/parse.rs
- tests/test.rs
Revert #393. It turns out bare `\r` is only prohibited inside of literals. In between tokens, bare `\r` is allowed and equivalent to `\n`.
The `schemafy_core` crate contains some bare `\r`. :disappointed: 
```console
$ hexyl schemafy_core-0.6.0/src/lib.rs 
┌────────┬─────────────────────────┬─────────────────────────┬────────┬────────┐
│00000000│ 70 75 62 20 6d 6f 64 20 ┊ 6f 6e 65 5f 6f 72 5f 6d │pub mod ┊one_or_m│
│00000010│ 61 6e 79 3b 0d 0d 0a    ┊                         │any;___ ┊        │
└────────┴─────────────────────────┴─────────────────────────┴────────┴────────┘
```
Notice the file ends with `\r\r\n`.
> Revert "Require \r whitespace to be followed by \n"

- src/fallback.rs
- tests/test.rs
> Account for multibyte chars in source_text() computation

- src/fallback.rs
- tests/test.rs
> Fix source_text treating span.lo as byte offset not char index

- src/fallback.rs
- src/parse.rs
- src/wrapper.rs
The parser would never call Ident::new with an invalid ident, which would panic. The parser is already implemented in a way that would return errors instead.
> Bypass Ident validation on identifiers created by parser

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
> Rename internal Ident::new -> Ident::new_checked

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
**Before:**
```console
thread 'main' panicked at ~/.cargo/registry/src/index.crates.io-6f17d22bba15001f/proc-macro2-1.0.69/src/fallback.rs:817:9:
"asdf()" is not a valid Ident
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
**After:**
```console
thread 'main' panicked at src/main.rs:2:13:
"asdf()" is not a valid Ident
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
> Track caller for Ident validation panics

- src/lib.rs
- src/wrapper.rs
This is allow-by-default for now in 2021 edition, but will become warn-by-default in 2024 edition.
> Turn on deny(unsafe_op_in_unsafe_fn)

- build.rs
- build/probe.rs
This prevents the disruptive failure mode from #398 with projects using old pinned versions of crates against newer versions of Rust nightly compiler.
The `anyhow` and `thiserror` build script have been using this approach for over 4 years, and while there were issues to iron out with the build script logic, with build systems (Cargo, Nix, rustc bootstrap), IDEs (rust-analyzer, IntelliJ, RustRover), and other tools (cargo-expand), at this point the approach is reliable enough to deploy in proc-macro2.
- https://github.com/dtolnay/anyhow/pull/91
- https://github.com/rust-lang/rust-analyzer/issues/12973
- https://github.com/intellij-rust/intellij-rust/pull/9235
- https://github.com/NixOS/nixpkgs/pull/78706
- https://github.com/dtolnay/anyhow/pull/157
- …
> Test for the specific proc_macro_span API expected by proc-macro2

- src/lib.rs
This regressed with https://github.com/rust-lang/rust/pull/113091 in nightly-2023-12-16. The doc(cfg()) from the type definition is no longer rendered.
> Restore documented cfg on LineColumn

- build.rs
- build/probe.rs
Copying over a fix from https://github.com/dtolnay/thiserror/pull/279 + https://github.com/dtolnay/thiserror/pull/280.
> Include env-dep:RUSTC_BOOTSTRAP in dep-info for sccache

- src/wrapper.rs
This is helpful for debugging in proc-macro code, where RUST_BACKTRACE=1 does not take effect.
```console
error: proc macro panicked
--> src/main.rs:4:1
|
4 | repro!();
| ^^^^^^^^
|
= help: message: compiler/fallback mismatch #854
```
> Include line number in compiler/fallback mismatch panic

- src/fallback.rs
- src/wrapper.rs
Closes https://github.com/dtolnay/syn/issues/1504.
**Before:**
```console
error: proc macro panicked
--> src/main.rs:4:13
|
4 |     let s = reparse!(" { ");
|             ^^^^^^^^^^^^^^^
|
= help: message: compiler/fallback mismatch #867
```
**After:**
```console
error: cannot parse string into token stream
--> src/main.rs:4:13
|
4 |     let s = reparse!(" { ");
|             ^^^^^^^^^^^^^^^
|
= note: this error originates in the macro `reparse` (in Nightly builds, run with -Z macro-backtrace for more info)
```
> Fix compiler/fallback mismatch when catching rustc lex error panic

- src/marker.rs
- tests/ui/test-not-send.stderr
Warning is new in nightly-2024-01-06 due to https://github.com/rust-lang/rust/pull/118297.
```console
warning: field `0` is never read
--> src/marker.rs:15:39
|
15 | pub(crate) struct ProcMacroAutoTraits(Rc<()>);
|                   ------------------- ^^^^^^
|                   |
|                   field in this struct
|
= note: `#[warn(dead_code)]` on by default
help: consider changing the field to be of unit type to suppress this warning while preserving the field numbering, or remove the field
|
15 | pub(crate) struct ProcMacroAutoTraits(());
|                                       ~~
```
> Work around new dead_code warning

- src/extra.rs
- src/lib.rs
- src/marker.rs
- tests/ui/test-not-send.stderr
No longer hits `dead_code` warning.
> Transpose ProcMacroAutoTraits struct and PhantomData

- build/probe.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
> Expose Span::byte_range

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
- tests/test.rs
Tracking issue: https://github.com/rust-lang/rust/issues/115268. This is being stabilized in Rust 1.79.
> Add `Literal::byte_character` constructor

- build.rs
- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
- tests/test.rs
Tracking issue: https://github.com/rust-lang/rust/issues/119750. This is being stabilized in Rust 1.79.
> Add `Literal::c_string` constructor

- src/lib.rs
This includes changes from:
- https://github.com/rust-lang/rust/pull/96433
- https://github.com/rust-lang/rust/pull/124051
> Sync documentation of Delimiter::None

- Cargo.toml
```console
warning: Cargo.toml: `default_features` is deprecated in favor of `default-features` and will not work in the 2024 edition
(in the `quote` dependency)
```
> Fix use of deprecated default_features in Cargo.toml

- Cargo.toml
- build.rs
- src/extra.rs
- src/lib.rs
- src/location.rs
As of recently, docs.rs defines a `docsrs` configuration for all builds, so we no longer need to do it using our own `package.metadata.docs.rs.rustdoc-args`.
> Rely on docs.rs to define --cfg=docsrs by default

- src/fallback.rs
- tests/test_size.rs
This is very significant because it drops the size of syn's TokenBuffer Entry from 40 bytes to 32 bytes.
https://github.com/dtolnay/syn/blob/2.0.65/src/buffer.rs#L14-L34
> Drop irrelevant capacity field from Ident representation

- src/lib.rs
Currently when used to implement a proc_macro, `Delimiter::None` simply doesn't do what it is documented to do.
While this is a rustc bug (rust-lang/rust#67062), it is a long standing one, and hard to discover.
This pull request adds a warning to inform users of this issue, with a link to the relevant issue, and a version number of the last known affected rustc version.
> Add a warning to `Delimiter::None` that rustc currently does not respect it.

- build.rs
Some of the descriptions are stale since #304.
> Bring build script comments up to date

- src/lib.rs
Closes #470.
Valid punctuation characters generated by:
```rust
use proc_macro::{Punct, Spacing, TokenStream};
use std::panic;
#[proc_macro]
pub fn punct_chars(_input: TokenStream) -> TokenStream {
for ch in '\0'..=char::MAX {
if let Ok(_) = panic::catch_unwind(|| {
let _ = Punct::new(ch, Spacing::Alone);
}) {
eprintln!("{:?}", ch);
}
}
TokenStream::new()
}
```
> Check valid punctuation character in Punct::new

- build/probe.rs
- src/wrapper.rs
Closes #397. Closes #402. Closes #407.
> Restore nightly behavior of Span::start and Span::end

- src/lib.rs
- src/wrapper.rs
Some of the type conversions in proc-macro2 are wasting time on too much unneeded checking where the input should be known to be valid, and at least one case of not enough checking. This commit is a first step toward understanding what conversions are taking place where, and giving names to different possible behaviors for some of these conversions.
> Write out explicit types in Into::into conversions

- src/fallback.rs
- src/lib.rs
- src/wrapper.rs
Following on from #477.
Some of these need to be changed to `from_str_unchecked`, and in some a check needs to be introduced to prevent hitting proc_macro::TokenStream::from_str with a potentially invalid string, which incorrectly panicks due to a rustc bug (https://github.com/rust-lang/rust/issues/58736).
> Spell out types in FromStr conversions

- src/fallback.rs
- src/wrapper.rs
This will make it possible to do additional non-proc_macro validation (using our own fallback parser) inside from_str_checked without relying on proc_macro's panicking codepath.
> Generalize from_str_checked error type

- src/wrapper.rs
Previously, pasting a panic message into a GitHub comment would cause it to get linked to some unrelated issue whose number is the same as the mismatch's line number.
> Change mismatch panic message to avoid github linkifying

- .github/workflows/ci.yml
I merged https://github.com/rust-fuzz/honggfuzz-rs/pull/99 and released a new version to crates.io so it should be good now. Thanks again
> Revert work around honggfuzz-rs issue

- build.rs
The docs.rs behavior that led to https://github.com/dtolnay/proc-macro2/issues/309 and required https://github.com/dtolnay/proc-macro2/pull/310 has been fixed in Cargo and docs.rs by https://github.com/rust-lang/cargo/pull/10395 + https://github.com/rust-lang/docs.rs/pull/1800. Since the fix, all the flags from `package.metadata.docs.rs.rustc-args` are now correctly applied to build script compilation as well, so we no longer need the additional logic to get `--cfg=procmacro2_semver_exempt` turned on during docs.rs builds.
https://github.com/dtolnay/proc-macro2/blob/6f40165f9fd5ad6a875d8385b0055c3870be69e2/Cargo.toml#L15-L16
> Revert "Work around doc build failure due to docs.rs flags change"

- build.rs
3e8962c (Clean up dep-info files from OUT_DIR, 2024-10-22) made the cleanup step a fatal operation when cleanup fails. Some filesystems (e.g. NFS v3) can run into timing issues under load where .nfs* dummy files can still exist for a short window of time after the probe command completes. This window is just large enough for a failure to occur in remove_all().
Add an environment variable that allows users to make the cleanup operation non-fatal.
> build: allow the cleanup step to be non-fatal

- build.rs
> Restore support for rustc older than 1.83
